spring.mail:
  host: localhost
  port: 1025
  username: username
  password: password
  properties.mail.smtp:
    ssl.trust: "*"
    auth: true
    starttls.enable: true
    connectiontimeout: 5000
    timeout: 3000
    writetimeout: 5000

app:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/todo
    username: appuser
    password: password
    maximum-pool-size: 15
  token:
    access-token-header-name-sent-by-client: Authorization
    access-token-header-name-generated-by-server: X-Access-Token
    authentication-scheme: Bearer
    key: jAOa=kms)dLxgE#*($#Qe_XH!uPq8Vdby@YlnvkANox^u3dQ53YU%n4B
    access-token-life-time: 900000
    refresh-token-life-time: 2592000000
    refresh-token-cookie-name: refresh-token


server:
  port: 8080
  servlet.context-path: /api/v1
  error:
    include-stacktrace: never



#logging:
#  level:
#    org.springframework.security.web.FilterChainProxy: DEBUG
#    com.zaxxer.hikari.pool: DEBUG
#
