app:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/todo
    username: appuser
    password: password
    maximum-pool-size: 15

server:
  port: 8080
  servlet.context-path: /api/v1


logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    com.zaxxer.hikari.pool: DEBUG

token:
  header-name: Authorization
  authentication-scheme: Bearer
  key: jAOa=kms)dLxgE#*($#Qe_XH!uPq8Vdby@YlnvkANox^u3dQ53YU%n4B
  access-token-life-time: 900000
  refresh-token-life-time: 2592000000
  refresh-token-cookie-name: refresh-token


