app:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/todo
    username: appuser
    password: password
    maximum-pool-size: 15

server:
  port: 8080
  servlet.context-path: /api/v1
  error:
    include-stacktrace: never



logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    com.zaxxer.hikari.pool: DEBUG

token:
  access-token-header-name-sent-by-client: Authorization
  access-token-header-name-generated-by-server: X-Access-Token
  authentication-scheme: Bearer
  key: jAOa=kms)dLxgE#*($#Qe_XH!uPq8Vdby@YlnvkANox^u3dQ53YU%n4B
  access-token-life-time: 60000
  refresh-token-life-time: 2592000000
  refresh-token-cookie-name: refresh-token


