app:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/todo
    username: appuser
    password: password
    maximum-pool-size: 15

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB106Dialect

server:
  port: 8080
  servlet:
    context-path: /api/v1


logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
    com:
      zaxxer:
        hikari:
          pool: DEBUG